### ISSUE TITLE
Problem with the list_snapshots_all() method

### ISSUE THREAD

**Issue by laleye** [scaleway/scaleway-sdk-python#186]
## Problem Description

When I use the `list_snapshots_all()` method without any parameters, it returns an empty list as result, whereas it's expected to return all the snapshots according to the method's description.

## Steps to Reproduce

```
from scaleway.instance.v1 import InstanceV1API as api
snapshots = api.list_snapshots(zone=default_zone)
```

## Expected Behavior

The `list_snapshots_all()` method should return all the snapshots with the default parameters.

**Comment by quantumsheep** [comment]
Hey 👋 Try to set the `organization` parameter to your organization id findable [here](https://console.scaleway.com/organization/settings).

**Comment by laleye** [comment]
Thanks,
It works with `organization` argument.

**Comment by quantumsheep** [comment]
Glad it worked :) It's optional because it can be retrieved from your `default_organization_id`, kind of confusing I agree
