### ISSUE TITLE
Mishandling of total_count value in instance API make the instance API unusable

### ISSUE THREAD

**Issue by havetc** [scaleway/scaleway-sdk-python#555]
On python 3.12, version 2.3.1 of the scaleway package

There seems to be a lot of instance api functions having issues with the `total_count` value "returned", I checked for at least  theses but there is probably more:

- `list_servers_types`
- `list_servers`
- `list_servers_all`
- `get_server_types_availability`

Checking the scaleway-go-sdk, it seems that for the instance API it is checking the "X-Total-Count"
https://github.com/scaleway/scaleway-sdk-go/blob/a057dbf8e7a1d8fabcfbdc7ba09416568a15fc61/scw/client.go#L255

In the function, after the http request is made I printed `res.headers` just before `res.json()` is sent to the Marshalling, and I just saw that indeed a "x-total-count" headers is present with the correct value (at least for  `get_server_types_availability` which I tested).

Could you fix the handling of this value for the whole instance API? As function calls crashes otherwise, it seems like a serious issue.

Could it also be made clear in the Readme that this package is supposed to be an alpha and is not production-ready ?

**Comment by gg3nx** [comment]
I can confirm issue for `get_server_types_availability` on 2.4.1:

```
File "/app/.venv/lib/python3.11/site-packages/scaleway/instance/v1/api.py", line 286, in get_server_types_availability
     return unmarshal_GetServerTypesAvailabilityResponse(res.json())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/app/.venv/lib/python3.11/site-packages/scaleway/instance/v1/marshalling.py", line 1785, in unmarshal_GetServerTypesAvailabilityResponse
     return GetServerTypesAvailabilityResponse(**args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: GetServerTypesAvailabilityResponse.__init__() missing 1 required positional argument: 'total_count'
 ```
