### ISSUE TITLE
Cannot add domain record.

### ISSUE THREAD

**Issue by adontz** [scaleway/scaleway-sdk-python#97]
It says "TypeError: Object of type RecordChangeAdd is not JSON serializable".

**Comment by quantumsheep** [comment]
Hey 👋  Thanks for reporting the issue, I will look into this tomorrow. Have a nice week-end.

**Comment by quantumsheep** [comment]
Fixed in #99! You can upgrade to 0.10.0:
```shell
pip install "scaleway>=0.10.0"
```
